export interface Resource {title:string;url:string;purpose:string}
const foundations={title:'Dive into Deep Learning: preliminaries',url:'https://d2l.ai/chapter_preliminaries/index.html',purpose:'Read the relevant section on tensors, calculus or automatic differentiation, then reproduce one calculation.'};
const architecture={title:'Stanford CS336: architecture lecture',url:'https://www.youtube.com/watch?v=ptFiH_bHnJw',purpose:'Watch the relevant architecture section, pause, and draw the tensor shapes. Full lecture; no unverified timestamp.'};
const resources:Record<string,Resource[]>={
 '01-foundations':[foundations,{title:'Micrograd: inspect a small autograd engine',url:'https://github.com/karpathy/micrograd',purpose:'Trace one forward expression and its backward computation in the source.'},{title:'Zero to Hero companion: build the autograd engine yourself',url:'https://github.com/victusfate/llm_mastery/blob/main/docs/zero-to-hero/l1-micrograd.md',purpose:'Follow our specification and checks for lectures 1 to 6, then verify your gradients against finite differences.'}],
 '02-transformer':[architecture,{title:'Attention Is All You Need',url:'https://arxiv.org/abs/1706.03762',purpose:'Connect the attention equation to the visual example.'},{title:'Zero to Hero companion: build a decoder and a tokenizer',url:'https://github.com/victusfate/llm_mastery/blob/main/docs/zero-to-hero/l7-gpt.md',purpose:'Use our study plan and causal-invariance check for lectures 7 and 8 before the module labs.'}],
 '03-pretraining':[{title:'DataTrove',url:'https://github.com/huggingface/datatrove',purpose:'Inspect readers, filters and deduplication stages.'},{title:'Stanford CS336: course recordings and materials',url:'https://cs336.stanford.edu/spring2025/',purpose:'Find the data and tokenization material; use the lecture list to choose a focused segment.'}],
 '04-systems':[{title:'PyTorch FSDP2 tutorial',url:'https://docs.pytorch.org/tutorials/intermediate/FSDP_tutorial.html',purpose:'Trace which state is sharded and when communication occurs.'},{title:'Stanford CS336: parallelism lecture',url:'https://www.youtube.com/watch?v=l1RJcDjzK8M',purpose:'Compare data and model parallelism using the lecture diagrams.'}],
 '05-scaling-evaluation':[{title:'Compute-optimal language model training',url:'https://arxiv.org/abs/2203.15556',purpose:'Identify the fitting assumptions and experimental scales.'},{title:'LM Evaluation Harness',url:'https://github.com/EleutherAI/lm-evaluation-harness',purpose:'Trace one task definition, metric and evaluation path.'}],
 '06-sft':[{title:'TRL documentation',url:'https://huggingface.co/docs/trl/index',purpose:'Inspect the training objective and masking behavior.'},{title:'Stanford CS336: SFT and RLHF lecture',url:'https://www.youtube.com/watch?v=Dfu7vC9jo4w',purpose:'Relate demonstration learning to preference-based post-training.'}],
 '07-rl':[{title:'Spinning Up: policy-gradient derivation',url:'https://spinningup.openai.com/en/latest/spinningup/rl_intro3.html',purpose:'Derive the estimator and explain where the baseline enters.'},{title:'Proximal Policy Optimization',url:'https://arxiv.org/abs/1707.06347',purpose:'Inspect what clipping changes in the surrogate objective.'}],
 '08-alignment':[{title:'Direct Preference Optimization',url:'https://arxiv.org/abs/2305.18290',purpose:'Trace the role of the reference policy in the pairwise objective.'},{title:'InstructGPT',url:'https://arxiv.org/abs/2203.02155',purpose:'Separate demonstrations, preference data, reward models and policy training.'}],
 '09-reasoning-rl':[{title:'DeepSeekMath',url:'https://arxiv.org/abs/2402.03300',purpose:'Read the group-relative optimization formulation and its assumptions.'},{title:'verl',url:'https://github.com/verl-project/verl',purpose:'Follow rollout, reward computation and policy update in an implementation.'}],
 '10-research':[{title:'OLMo-core',url:'https://github.com/allenai/OLMo-core',purpose:'Inspect one reproducible training configuration and its code path.'},{title:'Stanford CS336 materials',url:'https://cs336.stanford.edu/spring2025/',purpose:'Revisit the lecture or assignment corresponding to your research question.'}],
};
export function deeperResources(module:string):Resource[]{return resources[module] || [foundations]}
