export const labs = [
  {
    id: "01-01",
    module: 0,
    title: "Stable loss and verified gradients",
    file: "../docs/labs/01-01.md",
  },
  {
    id: "01-02",
    module: 0,
    title: "Train and compare small neural networks",
    file: "../docs/labs/01-02.md",
  },
  {
    id: "01-03",
    module: 0,
    title: "Convolution and spatial generalization",
    file: "../docs/labs/01-03.md",
  },
  {
    id: "01-04",
    module: 0,
    title: "Training controls and failure diagnosis",
    file: "../docs/labs/01-04.md",
  },
  {
    id: "02-01",
    module: 1,
    title: "A reversible tokenizer and small BPE vocabulary",
    file: "../docs/labs/02-01.md",
  },
  {
    id: "02-02",
    module: 1,
    title: "Causal decoder and attention parity",
    file: "../docs/labs/02-02.md",
  },
  {
    id: "02-03",
    module: 1,
    title: "Optimizer and resumable training loop",
    file: "../docs/labs/02-03.md",
  },
  {
    id: "02-04",
    module: 1,
    title: "Tiny language model and cached generation",
    file: "../docs/labs/02-04.md",
  },
  {
    id: "03-01",
    module: 2,
    title: "Aggregate sources with a provenance manifest",
    file: "../docs/labs/03-01.md",
  },
  {
    id: "03-02",
    module: 2,
    title: "Streaming normalization and restart safety",
    file: "../docs/labs/03-02.md",
  },
  {
    id: "03-03",
    module: 2,
    title: "Exact and near-duplicate auditing",
    file: "../docs/labs/03-03.md",
  },
  {
    id: "03-04",
    module: 2,
    title: "Inspectable quality filters",
    file: "../docs/labs/03-04.md",
  },
  {
    id: "03-05",
    module: 2,
    title: "Matched-budget pretraining comparison",
    file: "../docs/labs/03-05.md",
  },
  {
    id: "03-06",
    module: 2,
    title: "Checkpoint recovery and training observability",
    file: "../docs/labs/03-06.md",
  },
  {
    id: "04-01",
    module: 3,
    title: "Memory accounting and profiler baseline",
    file: "../docs/labs/04-01.md",
  },
  {
    id: "04-02",
    module: 3,
    title: "Optimize one measured training bottleneck",
    file: "../docs/labs/04-02.md",
  },
  {
    id: "04-03",
    module: 3,
    title: "A verified GPU kernel",
    file: "../docs/labs/04-03.md",
  },
  {
    id: "04-04",
    module: 3,
    title: "Distributed gradient equivalence",
    file: "../docs/labs/04-04.md",
  },
  {
    id: "04-05",
    module: 3,
    title: "DDP versus FSDP across two nodes",
    file: "../docs/labs/04-05.md",
  },
  {
    id: "04-06",
    module: 3,
    title: "Straggler and worker-failure investigation",
    file: "../docs/labs/04-06.md",
  },
  {
    id: "05-01",
    module: 4,
    title: "Small scaling grid and iso-compute pairs",
    file: "../docs/labs/05-01.md",
  },
  {
    id: "05-02",
    module: 4,
    title: "Fit and challenge a scaling prediction",
    file: "../docs/labs/05-02.md",
  },
  {
    id: "05-03",
    module: 4,
    title: "A reproducible evaluation entry point",
    file: "../docs/labs/05-03.md",
  },
  {
    id: "05-04",
    module: 4,
    title: "Paired uncertainty and seed variation",
    file: "../docs/labs/05-04.md",
  },
  {
    id: "05-05",
    module: 4,
    title: "Contamination and metric-integrity audit",
    file: "../docs/labs/05-05.md",
  },
  {
    id: "06-01",
    module: 5,
    title: "Generate instruction data with protected splits",
    file: "../docs/labs/06-01.md",
  },
  {
    id: "06-02",
    module: 5,
    title: "Inspect chat templates and supervised labels",
    file: "../docs/labs/06-02.md",
  },
  {
    id: "06-03",
    module: 5,
    title: "Full versus adapter fine-tuning",
    file: "../docs/labs/06-03.md",
  },
  {
    id: "06-04",
    module: 5,
    title: "Demonstration quality and behavioral regressions",
    file: "../docs/labs/06-04.md",
  },
  {
    id: "06-05",
    module: 5,
    title: "Freeze a reproducible reference policy",
    file: "../docs/labs/06-05.md",
  },
  {
    id: "07-01",
    module: 6,
    title: "Exact versus sampled bandit gradients",
    file: "../docs/labs/07-01.md",
  },
  {
    id: "07-02",
    module: 6,
    title: "REINFORCE and actor-critic in a chain",
    file: "../docs/labs/07-02.md",
  },
  {
    id: "07-03",
    module: 6,
    title: "PPO, GAE, and termination semantics",
    file: "../docs/labs/07-03.md",
  },
  {
    id: "07-04",
    module: 6,
    title: "Reward scale and rollout-length sensitivity",
    file: "../docs/labs/07-04.md",
  },
  {
    id: "08-01",
    module: 7,
    title: "Preference data and reward-model bias",
    file: "../docs/labs/08-01.md",
  },
  {
    id: "08-02",
    module: 7,
    title: "DPO from response log probabilities",
    file: "../docs/labs/08-02.md",
  },
  {
    id: "08-03",
    module: 7,
    title: "A minimal text PPO update",
    file: "../docs/labs/08-03.md",
  },
  {
    id: "08-04",
    module: 7,
    title: "Compare SFT, DPO, and PPO",
    file: "../docs/labs/08-04.md",
  },
  {
    id: "08-05",
    module: 7,
    title: "Construct and mitigate reward exploitation",
    file: "../docs/labs/08-05.md",
  },
  {
    id: "08-06",
    module: 7,
    title: "Behavioral alignment evaluation",
    file: "../docs/labs/08-06.md",
  },
  {
    id: "09-01",
    module: 8,
    title: "Arithmetic generator and verifier contract",
    file: "../docs/labs/09-01.md",
  },
  {
    id: "09-02",
    module: 8,
    title: "Base, SFT, and sampling baselines",
    file: "../docs/labs/09-02.md",
  },
  {
    id: "09-03",
    module: 8,
    title: "Group-relative policy updates",
    file: "../docs/labs/09-03.md",
  },
  {
    id: "09-04",
    module: 8,
    title: "Controlled reasoning-RL comparison",
    file: "../docs/labs/09-04.md",
  },
  {
    id: "09-05",
    module: 8,
    title: "Versioned rollout queue and staleness",
    file: "../docs/labs/09-05.md",
  },
  {
    id: "09-06",
    module: 8,
    title: "Optional trajectory distillation",
    file: "../docs/labs/09-06.md",
  },
  {
    id: "10-01",
    module: 9,
    title: "Register a falsifiable capstone question",
    file: "../docs/labs/10-01.md",
  },
  {
    id: "10-02",
    module: 9,
    title: "Reproduce the capstone baseline",
    file: "../docs/labs/10-02.md",
  },
  {
    id: "10-03",
    module: 9,
    title: "Run an intervention and ablations",
    file: "../docs/labs/10-03.md",
  },
  {
    id: "10-04",
    module: 9,
    title: "Prepare an external review package",
    file: "../docs/labs/10-04.md",
  },
  {
    id: "10-05",
    module: 9,
    title: "Publish a reproducible report",
    file: "../docs/labs/10-05.md",
  },
  {
    id: "10-06",
    module: 9,
    title: "Independent technical defense",
    file: "../docs/labs/10-06.md",
  },
];
